from inspect import signature
import sys


class VM:
    """
    The VM class used to represent the virtual machine. This class takes a set of opcodes generated by the
    compiler and interprets them. A set of opcodes would look like the below.

    (LOAD_VALUE, 0)
    (PRINT_VALUE, 0)

    The VM can be run using a set value of code that is supplied when the vm is initialized
    with the default run method. The run_once method is used to run a single set of opcodes
    provided on the spot.
    """

    def __init__(self, code):
        self.code = code
        self.stack = []
        self.frames = []
        self.frame_count = []
        self.pc = 0
        self.constant_table = []

    def LOAD_VALUE(self, argument):
        value = self.constant_table[argument]
        self.stack.append(value)
        self.pc += 1

    def PRINT_VALUE(self):
        value = self.stack.pop()

        print(value)

        self.pc += 1

    def ADD_TWO_VALUES(self):
        lhs = self.stack.pop()
        rhs = self.stack.pop()

        self.stack.append(lhs + rhs)

        self.pc += 1

    def SUB_TWO_VALUES(self):
        lhs = self.stack.pop()
        rhs = self.stack.pop()

        self.stack.append(lhs - rhs)

        self.pc += 1

    def MUL_TWO_VALUES(self):
        lhs = self.stack.pop()
        rhs = self.stack.pop()

        self.stack.append(lhs * rhs)

        self.pc += 1

    def DIV_TWO_VALUES(self):
        lhs = self.stack.pop()
        rhs = self.stack.pop()

        self.stack.append(lhs / rhs)

        self.pc += 1

    def SET_LOCAL(self, argument):
        value = self.stack[-1]

        self.stack.insert(argument, value)

        self.pc += 1

    def GET_LOCAL(self, argument):
        value = self.stack[argument]

        self.stack.append(value)

        self.pc += 1

    def run(self):
        while True:
            if self.pc >= len(self.code):
                sys.exit()

            instruction = self.code[self.pc]

            function = getattr(self, instruction[0])

            sig = signature(function)

            if len(sig.parameters) == 1:
                function(instruction[1])
            else:
                function()

    def run_once(self, code):
        while True:
            if self.pc >= len(code):
                break

            instruction = code[self.pc]

            function = getattr(self, instruction[0])

            sig = signature(function)

            if len(sig.parameters) == 1:
                function(instruction[1])
            else:
                function()
